// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nohctgbksxaouudbqkum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vaGN0Z2Jrc3hhb3V1ZGJxa3VtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1OTg0NTIsImV4cCI6MjA1ODE3NDQ1Mn0.MZK4VzZkFocHuwmbZbRvviqoj5GGXZLpCB9ZzKGTIOs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);